// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccybmrvhmwpiubiijltx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjeWJtcnZobXdwaXViaWlqbHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2Mjg1MTIsImV4cCI6MjA5NzIwNDUxMn0.W6SE5bUYJHHdcp-FlStZahOIWw1g5utaC6EM6qyri_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);